#!/bin/bash


./src/externalComm/Allwmake
./src/pyFMUSim/Allwmake

wmake application/test/test-dataLayer
wmake application/test/test-json
#./application/test/test-pyFMU/Allwmake
#wmake application/solver/solidFoamAdjustTime/
