#!/bin/bash

./src/testing/Allwmake
./src/externalComm/Allwmake
./src/embeddingPython/Allwmake

wmake application/test/test-dataLayer
wmake application/test/test-json
wmake application/test/test-zmq
wmake application/test/test-pythonNumpy

