#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory

rm -r lnInclude
wmakeLnIncludeAll 
conan install . -s compiler=gcc -s compiler.libcxx=libstdc++11 --build

wmake libso
