name: openfoam

on:
  push:
    branches: [ master ]
  pull_request:
    branches:
      - '*'

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: setup  openfoam
      run: |
        curl -s https://dl.openfoam.com/add-debian-repo.sh | sudo bash
        wget -q -O - https://dl.openfoam.com/add-debian-repo.sh | sudo bash
        sudo apt-get install openfoam2106-dev
    - name: compile library
      run: |
        # setup
        export WM_NCOMPPROCS=2
        python -m pip install --upgrade pip
        pip install oftest conan
        git submodule init
        git submodule update
        
        #install generator
        cd OpenFOAMGen/OpenFOAMGen
        conan export . myuser/OpenFOAMGen
        cd ../..

        # compile OpenFOAM
        openfoam2106 -c ./Allwmake
    # - name: test
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install oftest scipy casefoam
    #     openfoam2106 -c "py.test -m 'not slow'"
